FROM python:3.11

WORKDIR /code

COPY ./api/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./models /code/models
COPY ./data ./data
COPY ./api /code/api

WORKDIR /code/api

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]